//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class child
    {
        public child(string _name, string nickName, DateTime _birthdate, DateTime _enrolldate, bool _sex, int _idParent)
        {
            this.name = _name;
            this.nickname = nickName;
            this.birthdate = _birthdate;
            this.enrolldate = _enrolldate;
            this.sex = _sex;
            this.id_parent = _idParent;
        }
        public int id { get; set; }
        public string name { get; set; }
        public string nickname { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<System.DateTime> enrolldate { get; set; }
        public Nullable<bool> sex { get; set; }
        public Nullable<int> id_condition { get; set; }
        public int id_parent { get; set; }
        public Nullable<int> id_class { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual condition condition { get; set; }
        public virtual parent parent { get; set; }
    }
}
