 using MahApps.Metro.Controls;
using Rework.Models;
using Rework.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Rework.Windows
{
    /// <summary>
    /// Interaction logic for EditConditions.xaml
    /// </summary>
    public partial class EditConditions : MetroWindow
    {
        public EditConditions()
        {
            InitializeComponent();
            this.DataContext = new EditConditionsViewModel();
        }

        private void MetroDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            if (grid.Columns.Count() > 1)
            {
                ColumnTemplate.DisplayIndex = grid.Columns.Count - 1;
                grid.Columns[1].Visibility = Visibility.Collapsed;
                grid.Columns[3].Visibility = Visibility.Collapsed;
            }

        }

    }
}
